name: test-go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: build all go packages
        run: go build ./...
      - name: Run tests
        run: go test -v --cover ./...