// Code generated by buildmeta; DO NOT EDIT.
package main

var metadata = struct {
	VCSName   string
	VCSCommit string
	VCSTag    string
	VCSTime   string
	Env       string
	Service   string
}{VCSName: "git", VCSCommit: "d99844f9ad8ba7ee0d2be63b878ef7cfc6e92893", VCSTag: "", VCSTime: "2024-02-08T23:43:24Z", Env: "prod", Service: "test"}
